---
name: "handle_managed_demo_server_inquiry"
description: Handle inquiry from managed demo servers
enabled: false

trigger:
  type: core.st2.generic.inquiry

criteria:
  trigger.route:
    type: contains
    pattern: "ManagedDemoServerIssueKey"

action:
  ref: mock_portal.handle_managed_demo_server_inquiry
  parameters:
    route: "{{ trigger.route }}"
    inquiry_id: "{{ trigger.id }}"
